# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecgpt < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryuichi-maeda/ecgpt/releases/download/v0.1.0/ecgpt_Darwin_x86_64.tar.gz"
      sha256 "87ada49ccbe69d49e49e697c461277a7d0aea2496026ca42fb9c70855b8663c3"

      def install
        bin.install "ecgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryuichi-maeda/ecgpt/releases/download/v0.1.0/ecgpt_Darwin_arm64.tar.gz"
      sha256 "08dfcba4fd5141da42b94c2e6d872ab10cade39485f5f4d5f7afb860dd24694c"

      def install
        bin.install "ecgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryuichi-maeda/ecgpt/releases/download/v0.1.0/ecgpt_Linux_arm64.tar.gz"
      sha256 "b8f46a99b8761b27c7c6adb3cd49c4c5702cc6efcfee4d703fdd0f394da13b4b"

      def install
        bin.install "ecgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryuichi-maeda/ecgpt/releases/download/v0.1.0/ecgpt_Linux_x86_64.tar.gz"
      sha256 "cadea4f3c9af2eb7be6bd2cacb15e2d0e224335c52e8c28a64794adff932a04c"

      def install
        bin.install "ecgpt"
      end
    end
  end
end
