# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecgpt < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ryuichi-maeda/ecgpt/releases/download/v1.0.0/ecgpt_Darwin_arm64.tar.gz"
      sha256 "a4f2082fd1a776d250e22cbd9eb073c9d0e9d52041b643fdad06d2060b1f4d3a"

      def install
        bin.install "ecgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryuichi-maeda/ecgpt/releases/download/v1.0.0/ecgpt_Darwin_x86_64.tar.gz"
      sha256 "2daf567a11f038f514314414d3b01c124628eafd372c52a69b194b34dc15f16d"

      def install
        bin.install "ecgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryuichi-maeda/ecgpt/releases/download/v1.0.0/ecgpt_Linux_arm64.tar.gz"
      sha256 "5a71d45f320bd48c893145cfeca2e20e1630353d5cd60441e504eefe774ca974"

      def install
        bin.install "ecgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryuichi-maeda/ecgpt/releases/download/v1.0.0/ecgpt_Linux_x86_64.tar.gz"
      sha256 "18870300f9cd856a5f3787f298118b01e91ca710b6b48786321b3ce381be5cd3"

      def install
        bin.install "ecgpt"
      end
    end
  end
end
